// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDtpiHhHOvDw6H4vp1d9iuX1JqT6Kqxw',
    appId: '1:595504479761:web:a2f859e568cecce639fbb0',
    messagingSenderId: '595504479761',
    projectId: 'gymos-44758',
    authDomain: 'gymos-44758.firebaseapp.com',
    storageBucket: 'gymos-44758.firebasestorage.app',
    measurementId: 'G-GY691SYPY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBlNSeBYhvsGOKCqL1JbLF7ge78hh_Mcs',
    appId: '1:595504479761:android:9f118d0001ce960539fbb0',
    messagingSenderId: '595504479761',
    projectId: 'gymos-44758',
    storageBucket: 'gymos-44758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsS7jBGDMX0ubbV8Aw8rDE_UupFYB-dpk',
    appId: '1:595504479761:ios:6c51d03d658fde1a39fbb0',
    messagingSenderId: '595504479761',
    projectId: 'gymos-44758',
    storageBucket: 'gymos-44758.firebasestorage.app',
    iosBundleId: 'com.example.gympro',
  );
}
