import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'core/services/local_storage_service.dart';

/// Application entry point.
///
/// Initializes Firebase and platform services *before* running the app so that
/// providers/repositories can assume they are ready. Everything is wrapped in a
/// [ProviderScope] so Riverpod manages state across the whole tree.
Future<void> main() async {
  await runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Lock to portrait — a gym-floor app is used one-handed on phones.
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Lightweight key/value store for theme mode, onboarding flags, cache.
    await LocalStorageService.instance.init();

    // Initialize Firebase. `firebase_options.dart` is generated by
    // `flutterfire configure` — see README. Wrapped so the Core stage still
    // runs on a machine where Firebase isn't configured yet.
    try {
      await Firebase.initializeApp();
    } catch (e) {
      debugPrint('Firebase init skipped/failed (configure it via '
          'flutterfire): $e');
    }

    runApp(
      const ProviderScope(
        child: GymProApp(),
      ),
    );
  }, (error, stack) {
    // Central crash sink. Hook FirebaseCrashlytics here in production.
    debugPrint('Uncaught zone error: $error\n$stack');
  });
}
